from .areametric import (areaMe,area_chunks,areame_mixture)
from .dataseries import (dataseries,mixture,map_c_order,map_index_flat_to_array,mixture_given_dimension_index) 
from .methods import (ecdf, ecdf_p_, ecdf_p, ecdf_p_mixture_, quantile_function, quantile_value, inverse_quantile_function, inverse_quantile_value,inverse_quantile_mixture)
from .plotting import (plot_ecdf, plot_area, plot_ecdf_boxed, plot_mixture_area)
from .examples import (skinny, puffy, example_2d, example_3d, example_random_Nd)